In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import pickle

### Loading the dataset

In [2]:
df= pd.read_csv("Project_data.csv")
df.head(5)

,Unnamed: 0,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,0,Male,54.0,1,0,never,27.32,7.5,126,1
1,1,Female,52.0,0,0,never,27.32,5.7,145,0
2,2,Female,35.0,0,0,never,27.35,6.0,200,0
3,3,Male,44.0,0,0,never,31.87,5.7,140,1
4,4,Male,25.0,0,0,never,18.31,4.8,145,0

### EDA and PREPROCESSING

In [4]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48500 entries, 0 to 48499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               48500 non-null  object
 1   age                  48500 non-null  float64
 2   hypertension         48500 non-null  int64
 3   heart_disease        48500 non-null  int64
 4   smoking_history      48500 non-null  object
 5   bmi                  48500 non-null  float64
 6   HbA1c_level          48500 non-null  float64
 7   blood_glucose_level  48500 non-null  int64
 8   diabetes             48500 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 3.3+ MB

In [6]:
df.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,48500.000000,48500.000000,48500.000000,48500.000000,48500.000000,48500.000000,48500.000000
mean,43.795536,0.090887,0.049979,27.777405,5.670216,143.657753,0.175258
std,22.612654,0.287451,0.217905,6.873927,1.147768,45.880742,0.380191
min,0.080000,0.000000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,26.000000,0.000000,0.000000,24.100000,4.800000,100.000000,0.000000
50%,46.000000,0.000000,0.000000,27.320000,5.800000,145.000000,0.000000
75%,62.000000,0.000000,0.000000,30.240000,6.200000,159.000000,0.000000
max,80.000000,1.000000,1.000000,88.760000,9.000000,300.000000,1.000000

### Preprocessing

#### ENCODING THE QUALITATIVE COLUMNS

In [7]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Male,54.0,1,0,never,27.32,7.5,126,1
1,Female,52.0,0,0,never,27.32,5.7,145,0
2,Female,35.0,0,0,never,27.35,6.0,200,0
3,Male,44.0,0,0,never,31.87,5.7,140,1
4,Male,25.0,0,0,never,18.31,4.8,145,0
...,...,...,...,...,...,...,...,...,...
48495,Male,61.0,0,0,former,34.87,6.5,159,0
48496,Female,55.0,1,0,current,35.91,7.5,200,1
48497,Female,52.0,1,0,never,22.02,6.0,126,0
48498,Male,26.0,0,0,No Info,27.32,6.5,80,0
48499,Female,35.0,0,0,No Info,23.10,6.1,100,0

In [9]:
from sklearn.preprocessing  import LabelEncoder

gender_encoder = LabelEncoder()

df['gender'] = gender_encoder.fit_transform(df['gender'])

In [10]:
gender_classes = gender_encoder.classes_
gender_classes

array(['Female', 'Male', 'Other'], dtype=object)

In [11]:
sh_encoder = LabelEncoder()
df['smoking_history'] = sh_encoder.fit_transform(df['smoking_history'])

In [12]:
smokinghist_classes = sh_encoder.classes_

In [13]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,1,54.0,1,0,4,27.32,7.5,126,1
1,0,52.0,0,0,4,27.32,5.7,145,0
2,0,35.0,0,0,4,27.35,6.0,200,0
3,1,44.0,0,0,4,31.87,5.7,140,1
4,1,25.0,0,0,4,18.31,4.8,145,0
...,...,...,...,...,...,...,...,...,...
48495,1,61.0,0,0,3,34.87,6.5,159,0
48496,0,55.0,1,0,1,35.91,7.5,200,1
48497,0,52.0,1,0,4,22.02,6.0,126,0
48498,1,26.0,0,0,0,27.32,6.5,80,0
48499,0,35.0,0,0,0,23.10,6.1,100,0

In [12]:
df.corr()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
gender,1.000000,-0.015366,0.010839,0.081593,-0.073380,-0.025554,0.031303,0.031313,0.051495
age,-0.015366,1.000000,0.258321,0.244309,0.235912,0.334657,0.176426,0.179224,0.349642
hypertension,0.010839,0.258321,1.000000,0.117087,0.098626,0.158820,0.129103,0.123238,0.248188
heart_disease,0.081593,0.244309,0.117087,1.000000,0.025820,0.068105,0.105871,0.103801,0.209605
smoking_history,-0.073380,0.235912,0.098626,0.025820,1.000000,0.183114,0.066731,0.062810,0.131121
bmi,-0.025554,0.334657,0.158820,0.068105,0.183114,1.000000,0.139851,0.141239,0.282398
HbA1c_level,0.031303,0.176426,0.129103,0.105871,0.066731,0.139851,1.000000,0.253950,0.507961
blood_glucose_level,0.031313,0.179224,0.123238,0.103801,0.062810,0.141239,0.253950,1.000000,0.506760
diabetes,0.051495,0.349642,0.248188,0.209605,0.131121,0.282398,0.507961,0.506760,1.000000

#### Scaling the Data

In [14]:
features = df.drop(columns=['diabetes']) 
target = df['diabetes']

In [16]:
scaled_features

array([[ 1.17424514,  0.45127695,  3.16270807, ..., -0.06654276,
         1.59422727, -0.38486593],
       [-0.85031545,  0.36282999, -0.31618473, ..., -0.06654276,
         0.02594934,  0.02925544],
       [-0.85031545, -0.38896922, -0.31618473, ..., -0.0621784 ,
         0.287329  ,  1.22802783],
       ...,
       [-0.85031545,  0.36282999,  3.16270807, ..., -0.83758011,
         0.287329  , -0.38486593],
       [ 1.17424514, -0.78698057, -0.31618473, ..., -0.06654276,
         0.72296175, -1.38747557],
       [-0.85031545, -0.38896922, -0.31618473, ..., -0.68046306,
         0.37445555, -0.95155834]])

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

In [17]:
scaled_features_df = pd.DataFrame(scaled_features, columns=features.columns)
df = pd.concat([scaled_features_df, target.reset_index(drop=True)], axis=1)

In [18]:
df

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,1.174245,0.451277,3.162708,-0.229366,0.943209,-0.066543,1.594227,-0.384866,1
1,-0.850315,0.362830,-0.316185,-0.229366,0.943209,-0.066543,0.025949,0.029255,0
2,-0.850315,-0.388969,-0.316185,-0.229366,0.943209,-0.062178,0.287329,1.228028,0
3,1.174245,0.009042,-0.316185,-0.229366,0.943209,0.595386,0.025949,-0.079724,1
4,1.174245,-0.831204,-0.316185,-0.229366,0.943209,-1.377306,-0.758190,0.029255,0
...,...,...,...,...,...,...,...,...,...
48495,1.174245,0.760841,-0.316185,-0.229366,0.410124,1.031822,0.722962,0.334398,0
48496,-0.850315,0.495500,3.162708,-0.229366,-0.656046,1.183120,1.594227,1.228028,1
48497,-0.850315,0.362830,3.162708,-0.229366,0.943209,-0.837580,0.287329,-0.384866,0
48498,1.174245,-0.786981,-0.316185,-0.229366,-1.189132,-0.066543,0.722962,-1.387476,0
48499,-0.850315,-0.388969,-0.316185,-0.229366,-1.189132,-0.680463,0.374456,-0.951558,0

#### Balancing the Data

In [22]:
df['diabetes'].value_counts()

diabetes
0    40000
1     8500
Name: count, dtype: int64

In [23]:
df_minority = df[df['diabetes'] == 1]
df_majority = df[df['diabetes'] == 0]

In [25]:
from sklearn.utils import resample

df_up_sampled = resample(df_minority, n_samples=20000, random_state=123456)
df_up_sampled

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
35052,1.174245,1.601088,3.162708,-0.229366,0.943209,0.583747,2.204113,2.099862,1
39007,-0.850315,1.203076,-0.316185,-0.229366,-1.189132,5.386001,2.901126,2.971697,1
25966,-0.850315,0.628171,-0.316185,-0.229366,0.943209,0.893617,0.810088,-0.297682,1
17656,1.174245,1.335747,-0.316185,-0.229366,1.476294,-0.066543,0.722962,0.029255,1
20664,1.174245,-0.123628,3.162708,-0.229366,-1.189132,0.775779,2.204113,2.535780,1
...,...,...,...,...,...,...,...,...,...
5799,-0.850315,1.512641,-0.316185,-0.229366,-0.656046,-0.011261,0.722962,3.407614,1
7283,-0.850315,-0.477416,-0.316185,-0.229366,1.476294,2.181104,0.113076,2.099862,1
24561,-0.850315,1.601088,-0.316185,-0.229366,-1.189132,-1.189639,0.722962,1.228028,1
16571,1.174245,1.601088,3.162708,-0.229366,0.410124,-0.488431,1.594227,0.247214,1
40145,-0.850315,1.335747,-0.316185,-0.229366,0.943209,0.364074,2.204113,-0.384866,1

In [26]:
df_balanced = pd.concat([df_majority, df_up_sampled])
df_balanced

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
1,-0.850315,0.362830,-0.316185,-0.229366,0.943209,-0.066543,0.025949,0.029255,0
2,-0.850315,-0.388969,-0.316185,-0.229366,0.943209,-0.062178,0.287329,1.228028,0
4,1.174245,-0.831204,-0.316185,-0.229366,0.943209,-1.377306,-0.758190,0.029255,0
6,-0.850315,-0.123628,-0.316185,-0.229366,-1.189132,-0.066543,0.722962,0.029255,0
7,-0.850315,-1.229215,-0.316185,-0.229366,-1.189132,1.248585,-1.455202,-0.384866,0
...,...,...,...,...,...,...,...,...,...
5799,-0.850315,1.512641,-0.316185,-0.229366,-0.656046,-0.011261,0.722962,3.407614,1
7283,-0.850315,-0.477416,-0.316185,-0.229366,1.476294,2.181104,0.113076,2.099862,1
24561,-0.850315,1.601088,-0.316185,-0.229366,-1.189132,-1.189639,0.722962,1.228028,1
16571,1.174245,1.601088,3.162708,-0.229366,0.410124,-0.488431,1.594227,0.247214,1
40145,-0.850315,1.335747,-0.316185,-0.229366,0.943209,0.364074,2.204113,-0.384866,1

In [27]:
df_balanced['diabetes'].value_counts()

diabetes
0    40000
1    20000
Name: count, dtype: int64

In [28]:
df_balanced.corr()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
gender,1.000000,-0.000652,0.015112,0.089643,-0.064611,-0.023418,0.039846,0.036633,0.060649
age,-0.000652,1.000000,0.262078,0.256956,0.240065,0.308479,0.252607,0.241453,0.436757
hypertension,0.015112,0.262078,1.000000,0.114432,0.107231,0.164905,0.162148,0.143950,0.267958
heart_disease,0.089643,0.256956,0.114432,1.000000,0.034449,0.072613,0.126616,0.126356,0.224763
smoking_history,-0.064611,0.240065,0.107231,0.034449,1.000000,0.184336,0.096650,0.083542,0.167010
bmi,-0.023418,0.308479,0.164905,0.072613,0.184336,1.000000,0.188944,0.179667,0.331508
HbA1c_level,0.039846,0.252607,0.162148,0.126616,0.096650,0.188944,1.000000,0.316386,0.581577
blood_glucose_level,0.036633,0.241453,0.143950,0.126356,0.083542,0.179667,0.316386,1.000000,0.549038
diabetes,0.060649,0.436757,0.267958,0.224763,0.167010,0.331508,0.581577,0.549038,1.000000

#### Splitting the Data

In [29]:
x = df.drop('diabetes', axis=1)
y = df['diabetes']

In [30]:
# split the data into train and test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.7, random_state=123456)

### Creating the model

In [31]:
from sklearn.linear_model import LogisticRegression

def create_model_logistic_regression():
    model = LogisticRegression(max_iter=1000)
    model.fit(x_train, y_train)
    return model

In [32]:
from sklearn.naive_bayes import GaussianNB

def create_model_nb():
    model = GaussianNB()
    model.fit(x_train, y_train)
    return model

In [33]:
from sklearn.neighbors import KNeighborsClassifier

def create_model_knn():
    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(x_train, y_train)
    return model

In [34]:
from sklearn.svm import SVC

def create_model_svm():
    model = SVC()
    model.fit(x_train, y_train)
    return model

In [35]:
from sklearn.tree import DecisionTreeClassifier

def create_model_decision_tree():
    model = DecisionTreeClassifier(max_depth=50)
    model.fit(x_train, y_train)
    return model

In [36]:
from sklearn.ensemble import RandomForestClassifier

def create_model_random_forest():
    model = RandomForestClassifier(n_estimators=100)
    model.fit(x_train, y_train)
    return model

In [37]:
from sklearn.ensemble import GradientBoostingClassifier

def create_model_grandient_boost():
    model = GradientBoostingClassifier()
    model.fit(x_train, y_train)
    return model

In [38]:
from xgboost import XGBClassifier

def create_model_xgboost():
    model = XGBClassifier()
    model.fit(x_train, y_train)
    return model

### Model Evaluation

In [39]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

def evaluate_model(model):
    # training accuracry
    y_pred = model.predict(x_train)
    y_true = y_train

    # calculate training accuracy
    training_accuracy = accuracy_score(y_true, y_pred)

    # testing accuracy
    y_pred = model.predict(x_test)
    y_true = y_test

    # get the performance metrics for testing
    testing_accuracy = accuracy_score(y_true, y_pred)
    testing_precision = precision_score(y_true, y_pred)
    testing_recall = recall_score(y_true, y_pred)
    testing_f1 = f1_score(y_true, y_pred)
    testing_roc = roc_auc_score(y_true, y_pred)

    return training_accuracy, testing_accuracy, testing_precision, testing_recall, testing_f1, testing_roc

In [40]:
models = [
    ("Logistic Regression", create_model_logistic_regression(), (0, 0)),
    ("Naive Bayes", create_model_nb(), (0, 1)),
    ("KNN", create_model_knn(), (1, 0)),
    ("SVM", create_model_svm(), (1, 1)),
    ("Decision Tree", create_model_decision_tree(), (2, 0)),
    ("Random Forest", create_model_random_forest(), (2, 1)),
    ("XGBoost", create_model_xgboost(), (4, 1))
]

In [41]:
performance_data = []
for model_name, model, position in models:
    train_accuracy, test_accuracy, precision, recall, f1, roc = evaluate_model(model)
    performance_data.append([
        model_name, f"{train_accuracy * 100:0.2f}%", f"{test_accuracy * 100:0.2f}%", precision, recall, f1, roc
    ])
    
performance_chart = pd.DataFrame(performance_data, 
            columns=["Model", "Train Accuracy", "Test Accuracy", "Precision", "Recall", "F1", "ROC"])
performance_chart

,Model,Train Accuracy,Test Accuracy,Precision,Recall,F1,ROC
0,Logistic Regression,93.00%,92.87%,0.862020,0.709048,0.778087,0.842385
1,Naive Bayes,88.09%,87.58%,0.638391,0.680967,0.658992,0.799227
2,KNN,94.60%,92.53%,0.842691,0.708268,0.769655,0.839993
3,SVM,93.66%,93.37%,0.936647,0.668877,0.780432,0.829599
4,Decision Tree,99.94%,91.94%,0.770939,0.771841,0.771390,0.861392
5,Random Forest,99.94%,94.00%,0.905905,0.735959,0.812137,0.859804
6,XGBoost,96.49%,94.21%,0.908832,0.746490,0.819700,0.865236

In [42]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [43]:
from sklearn.ensemble import RandomForestClassifier


model = RandomForestClassifier(n_estimators=100)
model.fit(x_train, y_train)

RandomForestClassifier()

In [44]:
with open('gender_encoder.pkl', 'wb') as f:
    pickle.dump(gender_encoder, f)
with open('smoking_encoder.pkl', 'wb') as f:
    pickle.dump(sh_encoder, f)

with open('diabetes_model.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)